In [ ]:
#searching for elements in an array using numpy
import numpy as np

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,4,4])
x=np.where(a==4)
print(x)

(array([3, 5, 6]),)


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==1)
print(x)

(array([0, 2, 4, 6]),)


In [6]:
a=np.array([6,7,8,9])
x=np.searchsorted(a,7)
print(x)

1


In [7]:
np.searchsorted(a, 7, side='right')

np.int64(2)

In [8]:
a=np.array([1,2,4,6,7,10])
x=np.searchsorted(a,[3,5,8])
print(x)

[2 3 5]


sorting of numpy arrays


In [10]:
a=np.array([3,2,0,1])
print(np.sort(a))

[0 1 2 3]


In [11]:
a=np.array(['banana', 'apple', 'cherry'])
print(np.sort(a))

['apple' 'banana' 'cherry']


In [12]:
a=np.array([True, False, True])
print(np.sort(a))

[False  True  True]


In [13]:
#sorting of 2-dimensional numpy arrays
a=np.array([[3,2,4],[5,0,1]])
print(np.sort(a))

[[2 3 4]
 [0 1 5]]


filtering of numpy array


In [15]:
a=np.array([41,42,43,44])
x=[True,False,True,False]
new_array=a[x]
print(new_array)


[41 43]


In [16]:
#filtering of numpy array using loops
a=np.array([41,42,43,44])
new_array=[]
for i in a:
    if i%2==0:
        new_array.append(True)
    else:
        new_array.append(False)

n_a=a[new_array]
print(n_a,'  ',new_array)        




[42 44]    [False, True, False, True]


In [17]:
#filtering directly from array
a=np.array([41,42,43,44])
fil_a=a>42
n_a=a[fil_a]
print(n_a,' ',fil_a)

[43 44]   [False False  True  True]


In [18]:
#creating filter array  to display only even numbers
a=np.array([1,2,3,4,5,6,7,8])
x=a%2==0
print(a[x])

[2 4 6 8]


In [19]:
a=[x for x in range(1,101)]

In [21]:
print([x for x in a if x%2==0])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
